### ISSUE TITLE
Corrigir digitação das palavras no jogo

### ISSUE THREAD

**Issue by leticia-pontes** [leticia-pontes/eng-software-3bcc#35]
## Descrição
A digitação das palavras no jogo quebrou.
* A fonte não está padronizada.
* A validação das letras não está ocorrendo.
* Ao submeter a última palavra, o jogo não finaliza (por mais que a validação não esteja sendo feita, espera-se que um alerta de "Fim de Jogo" apareça).

## Objetivo
Corrigir a digitação do jogo.

### Subtasks
- [x] Padronizar a fonte;
- [x] Validar as letras;
    - [x] Letras na posição correta;
    - [x] Letras na posição errada;
    - [ ] #39
- [x] Validar palavra correta;
    - [x] Mostrar mensagem de "Fim de Jogo".

## Comportamento Esperado
Ter um jogo funcional

## Comportamento Atual
A digitação das letras nas caixas está funcionando (escrevendo e apagando), mas as letras não estão sendo validadas.

## Passos para Reproduzir o Problema
1. Abrir o prompt de comando na pasta eng-software-3bcc
2. Digitar python manage.py runserver
3. Abrir o site (por padrão localhost:8000)
4. Clicar em ENTRE e fazer login (ou clicar em CADASTRE-SE, fazer o cadastro e efetuar o login)
    Se já houver um usuário de testes cadastrado, utilizá-lo.

## Contexto Adicional
![Captura de tela 2024-09-27 215731](https://github.com/user-attachments/assets/60dcc3bc-8bb5-4d82-a466-384c4057d9bd)

## Possível Causa do Erro
![Captura de tela 2024-09-27 220912](https://github.com/user-attachments/assets/bc4045da-15f5-492e-95c6-4ae50c546d19)

## Ambiente
- **Sistema Operacional:** (Windows, Mac, Linux)
- **Navegador (se aplicável):** (Chrome, Firefox, etc.)
- **Versão do Projeto:**
- **Outros:**

## Referências (opcional)
